project_id = "qfxstzlqlfbivqnvccwd"

[functions.extract-brochure-specs]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.create-first-admin]
verify_jwt = false

[functions.resend-invite]
verify_jwt = false
