-- Add comprehensive technical specification columns for combines
ALTER TABLE public.equipment
ADD COLUMN IF NOT EXISTS engine_cylinders integer,
ADD COLUMN IF NOT EXISTS max_torque_nm integer,
ADD COLUMN IF NOT EXISTS feeder_width_mm integer,
ADD COLUMN IF NOT EXISTS rasp_bar_count integer,
ADD COLUMN IF NOT EXISTS threshing_drum_diameter_mm integer,
ADD COLUMN IF NOT EXISTS threshing_drum_width_mm integer,
ADD COLUMN IF NOT EXISTS threshing_area_m2 numeric,
ADD COLUMN IF NOT EXISTS rotor_length_mm integer,
ADD COLUMN IF NOT EXISTS separator_area_m2 numeric,
ADD COLUMN IF NOT EXISTS straw_walker_count integer,
ADD COLUMN IF NOT EXISTS straw_walker_area_m2 numeric,
ADD COLUMN IF NOT EXISTS sieve_area_m2 numeric,
ADD COLUMN IF NOT EXISTS unloading_rate_ls numeric,
ADD COLUMN IF NOT EXISTS auger_reach_m numeric,
ADD COLUMN IF NOT EXISTS chopper_width_mm integer,
ADD COLUMN IF NOT EXISTS max_slope_percent integer,
ADD COLUMN IF NOT EXISTS transport_width_mm integer,
ADD COLUMN IF NOT EXISTS transport_height_mm integer,
ADD COLUMN IF NOT EXISTS transport_length_mm integer,
ADD COLUMN IF NOT EXISTS header_width_min_m numeric,
ADD COLUMN IF NOT EXISTS header_width_max_m numeric,
ADD COLUMN IF NOT EXISTS detailed_specs jsonb DEFAULT '{}'::jsonb;